version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
        - npm --prefix ./frontend install
        - npm --prefix ./backend install
  pre_build:
    commands:
        - npm --prefix ./frontend run lint
        - npm --prefix ./backend run lint
        - npm --prefix ./frontend test -- --watchAll=false
  build:
    commands:
        - npm --prefix ./frontend run build
        - npm --prefix ./backend run tsc


artifacts:
  files:
    - appspec.yml
    - frontend/node_modules/**/*
    - frontend/build/**/*
    - backendend/node_modules/**/*
    - backendend/build/**/*
    - scripts/*